import './globals.css'
import StoryblokBridge from '../components/StoryblokBridge'

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <StoryblokBridge />
      <body>{children}</body>
    </html>
  )
}
