import './../globals.css'
import { i18n } from "../../i18n-config";

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }))
}
export default function RootLayout( { children, params}: { children: React.ReactNode, params: { lang: string } } ) {
  return (
    <html lang={params.lang}>
    <head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app"/>
      <link rel="icon" href="/favicon.ico"/>
    </head>
    <body>{ children }</body>
    </html>
  )
}
